protected/modules/onlinehelp/models/OnlineHelp.php
<?php

/**
 * This is the model class for table "{{onlinehelp}}".
 *
 * The followings are the available columns in table '{{onlinehelp}}':
 * @property integer $id
 * @property string $title
 * @property string $requestId
 * @property boolean $isPageHelp
 * @property integer $sequenceNbr
 * @property string $elementId
 * @property string $guiderPosition
 * @property string $content
 * @property integer $tsCreated
 * @property integer $userIdCreated
 * @property integer $tsUpdated
 * @property integer $userIdUpdated
 */
class OnlineHelp extends Model //CActiveRecord
{
	// {{{ *** Members ***
    /**
     * @var string
     */
    public $nameFields = "title;requestId";
    /**
     * @var string
     */
    public $nameFormat = "{1} ({2})";

    public $saveAsNew=false;

    // }}} End Members
	// {{{ *** Methods ***
	// {{{ model
	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return OnlineHelp the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	} // }}} 	    
	// {{{ tableName
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return '{{onlinehelp}}';
	} // }}} 
    // {{{ behaviors
    public function behaviors()
    {
        return array();
        return array(
            'TimestampBehavior' => array(
                'class' => 'application.components.behaviors.TimestampBehavior',
                'tsCreateAttribute' => 'tsCreated',
                'userCreateAttribute' => 'userIdCreated',
                'tsUpdateAttribute' => 'tsUpdated',
                'userUpdateAttribute' => 'userIdUpdated',
            )
        );
    } // }}} 
    // {{{ rules
	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('title, content', 'required'),
            array('title, requestId, elementId', 'length', 'max'=>255),
            array('guiderPosition', 'length', 'max'=>15),
            array('isPageHelp', 'boolean'),
            array('sequenceNbr', 'numerical', 'integerOnly'=>true, 'min'=>1),
            array('saveAsNew', 'safe'),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id, title, requestId, isPageHelp, sequenceNbr, elementId, guiderPosition, content, tsCreated, userIdCreated, tsUpdated, userIdUpdated', 'safe', 'on'=>'search'),
		);
	} // }}} 
	// {{{ relations
	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
                return array(
                    'userCreated'=>array(self::BELONGS_TO,'User','userIdCreated'),
                    'userUpdated'=>array(self::BELONGS_TO,'User','userIdUpdated'),
		);
	} // }}} 
	// {{{ attributeLabels
	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => Yii::t('onlinehelp','ID'),
			'title' => Yii::t('onlinehelp','Title'),
            'requestId' => Yii::t('onlinehelp','Request ID'),
            'isPageHelp' => Yii::t('onlinehelp','Help for complete page'),
            'sequenceNbr' => Yii::t('onlinehelp','Sequence No.'),
            'elementId' => Yii::t('onlinehelp','Element ID'),
            'guiderPosition' => Yii::t('onlinehelp','Guider Position'),
			'content' => Yii::t('onlinehelp','Content'),
			'tsCreated' => Yii::t('onlinehelp','Created On'),
			'userIdCreated' => Yii::t('onlinehelp','Created By'),
			'tsUpdated' => Yii::t('onlinehelp','Updated On'),
            'userIdUpdated' => Yii::t('onlinehelp','Updated By'),
            'saveAsNew' => Yii::t('onlinehelp','Save as New'),
		);
	} // }}} 
	// {{{ search
	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
        // Warning: Please modify the following code to remove attributes that
        // should not be searched.

        $criteria=new CDbCriteria;

        $criteria->compare('id',$this->id);
        $criteria->compare('title',$this->title,true);
        $criteria->compare('requestId',$this->requestId,true);
        $criteria->compare('isPageHelp',$this->isPageHelp,true);
        $criteria->compare('sequenceNbr',$this->sequenceNbr,true);
        $criteria->compare('elementId',$this->elementId,true);
        $criteria->compare('content',$this->content,true);
        $criteria->compare('tsCreated',$this->tsCreated);
        $criteria->compare('userIdCreated',$this->userIdCreated);
        $criteria->compare('tsUpdated',$this->tsUpdated);
        $criteria->compare('userIdUpdated',$this->userIdUpdated);

        return new CActiveDataProvider($this, array(
            'criteria'=>$criteria,
            'sort'=>array(
                'defaultOrder'=>'requestId, sequenceNbr',
            ),
	    ));
    } // }}} 
    // {{{ getRecordName
    public function getRecordName()
    {
        $name = $this->requestId.'/#'.$this->sequenceNbr.'/'.$this->title;
        if(trim($this->elementId)!=='')
            $name .= '/'.$this->elementId;
        return $name;
    } // }}} 
    // {{{ getGuiderPositionOptions
    /**
     * Returns an array of Guider position names, indexed by position codes
     *
     * @return mixed
     */
    public function getGuiderPositionOptions()
    {
        return array(
            11=>"Top Left (11 o'clock)",
            12=>"Top (12 o'clock)",
            1=>"Top Right (1 o'clock)",
            2=>"Right Top (2 o'clock)",
            3=>"Right (3 o'clock)",
            4=>"Right Bottom (4 o'clock)",
            5=>"Bottom Right (5 o'clock)",
            6=>"Bottom (6 o'clock)",
            7=>"Bottom Left (7 o'clock)",
            8=>"Left Bottom (8 o'clock)",
            9=>"Left (9 o'clock)",
            10=>"Left Top (10 o'clock)"
        );
    } // }}} 
    // }}} End Methods
}

protected/modules/onlinehelp/controllers/EditorController.php
<?php

class EditorController extends Controller
{
    // {{{ *** Members ***
    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout='//layouts/column2';

    /**
     * @var CActiveRecord the currently loaded data model instance.
     */
    private $_model;

    public $defaultAction = 'admin';
    // }}} End Members
    // {{{ filters
    /**
     * @return array action filters
     */
    public function filters()
    {
        return array(
            'accessControl', // perform access control for CRUD operations
        );
    } // }}} 
    // {{{ accessRules
    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules()
    {
        return array();
        return array(
            array('allow',  // allow all users to perform 'index' and 'view' actions
                'actions'=>array('index','view'),
                'users'=>array('*'),
            ),
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions'=>array('create','update','admin','delete','preview'),
                'users'=>array('@'),
            ),
            /*
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions'=>array('admin','delete'),
                'users'=>array('admin'),
            ),
            */
            array('deny',  // deny all users
                'users'=>array('*'),
            ),
        );
    } // }}} 
    // {{{ *** Actions ***
    // {{{ actionView
    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id)
    {
        $this->render('view',array(
            'model'=>$this->loadModel($id),
        ));
    } // }}} 
    // {{{ actionCreate
    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate()
    {
        // $this->checkAccess('onlinehelpitem.create');
        $model=new OnlineHelp;
        if(isset($_GET['OnlineHelp'])) {
            $model->attributes = $_GET['OnlineHelp'];
            $model->requestId = str_replace('.', '/', $model->requestId);
            $model->isPageHelp = true;
        }

        $model->requestId = preg_replace("/\/id\/.*$/",'',$model->requestId);

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if(isset($_POST['OnlineHelp']))
        {
            $model->attributes=$_POST['OnlineHelp'];
            if($model->save()) {
                $msg = array(
                    '<h4>',
                    Yii::t('onlinehelp','Creating New Online Help Page'),
                    '</h4>',
                    Yii::t('onlinehelp','The Online Help Page {recordName} has been created.',array('{recordName}'=>$model->recordName))
                );
                if(preg_match("/update|view/",$model->requestId))
                    $msg[] = Yii::t('onlinehelp','The request ID contains view or update. To see this help text, open the respective create or update page.');
                Yii::app()->user->setFlash( 'success', join( "\n", $msg ) );
                $requestId = preg_replace("/(update|view.*)$/",'admin',$model->requestId);
                $this->redirect(array('/'.$requestId));
            } else {
                Yii::app()->user->setFlash(
                    'error',
                    array(
                        Yii::t('onlinehelp','Error Creating New Online Help Page'),
                        Yii::t('onlinehelp','Couldn\' create new Online Help Page.')
                    )
                );
            }
        }

        $this->render('create',array(
            'model'=>$model,
        ));
    } // }}} 
    // {{{ actionUpdate
    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id)
    {
        // $this->checkAccess('onlinehelpitem.update');
        $model=$this->loadModel($id);

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if(isset($_POST['OnlineHelp']))
        {
            $model->attributes=$_POST['OnlineHelp'];
            if($model->saveAsNew==true) {
                $model = new OnlineHelp;
                $model->attributes=$_POST['OnlineHelp'];
                unset($model->id);
            }
            if($model->save()) {
                $msg = array(
                    '<h4>',
                    Yii::t('onlinehelp','Updating an Online Help Page'),
                    '</h4>',
                    Yii::t('onlinehelp','The Online Help Page {recordName} has been updated.',array('{recordName}'=>$model->recordName))
                );
                if(preg_match("/update|view/",$model->requestId))
                    $msg[] = Yii::t('onlinehelp','The request ID contains view or update. To see this help text, open the respective create or update page.');
                Yii::app()->user->setFlash( 'success', join( "\n", $msg ) );
                $requestId = preg_replace("/(update|view.*)$/",'admin',$model->requestId);
                $this->redirect(array('/'.$requestId));
            } else {
                Yii::app()->user->setFlash(
                    'error',
                    array(
                        Yii::t('onlinehelp','Error Updating Online Help Page'),
                        Yii::t('onlinehelp','Couldn\' update Online Help Page {recordName}.',array('{recordName}'=>$model->recordName))
                    )
                );
            }
        }

        $this->render('update',array(
            'model'=>$model,
        ));
    } // }}}
    // {{{ actionPreview
    public function actionPreview()
    {
        $parser=new CMarkdownParser;
        echo $parser->safeTransform($_POST['OnlineHelp'][$_GET['attribute']]);
    } // }}} 
    // {{{ actionDelete
    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($id)
    {
        // $this->checkAccess('onlinehelpitem.delete');
        if(Yii::app()->request->isPostRequest)
        {
            // we only allow deletion via POST request
            $result = $this->loadModel($id)->delete();

            // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
            if(!isset($_GET['ajax'])) {
                if($result==true) {
                    Yii::app()->user->setFlash(
                        'success',
                        array(
                            Yii::t('onlinehelp','Deleting Online Help Page'),
                            Yii::t('onlinehelp','The Online Help Page {recordName} has been deleted.',array('{recordName}'=>$model->recordName))
                        )
                    );
                    $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
                } else {
                    Yii::app()->user->setFlash(
                        'error',
                        array(
                            Yii::t('onlinehelp','Error Deleting Online Help Page'),
                            Yii::t('onlinehelp','The Online Help Page {recordName} couldn\'t be deleted.',array('{recordName}'=>$model->recordName))
                        )
                    );
                }
            }
        }
        else
            throw new CHttpException(400,Yii::t('onlinehelp','Invalid request. Please do not repeat this request again.'));
    } // }}} 
    // {{{ actionIndex
    /**
     * Lists all models.
     */
    public function actionIndex()
    {
        // $this->checkAccess('onlinehelpitem.list');
        $dataProvider=new CActiveDataProvider('OnlineHelp');
        $this->render('index',array(
            'dataProvider'=>$dataProvider,
        ));
    } // }}} 
    // {{{ actionAdmin
    /**
     * Manages all models.
     */
    public function actionAdmin()
    {
        //$this->checkAccess('onlinehelpitem.admin');
        $model=new OnlineHelp('search');
        $model->unsetAttributes();  // clear any default values
        if(isset($_GET['OnlineHelp']))
            $model->attributes=$_GET['OnlineHelp'];

        $this->render('admin',array(
            'model'=>$model,
        ));
    } // }}}
    // {{{ actionToggleUserOnlineHelpPage
    public function actionToggleUserOnlineHelpPage($requestId, $isChecked)
    {
        $requestId = str_replace('.', '/', $requestId);
        if( $isChecked=='checked' )
            $isChecked = 1;
        else
            $isChecked = 0;
        if($isChecked==0) {
            $sql = "INSERT INTO `{{useronlinehelptohide}}` (userId, requestId) VALUES ( :userId, :requestId )";
        } else {
            $sql = "DELETE FROM `{{useronlinehelptohide}}` WHERE userId=:userId AND requestId=:requestId";
        }
        $userIdColumn = Yii::app()->modules['onlinehelp']['userIdColumn'];
        if(is_null($userIdColumn)) {
            $module = get_class_vars ( 'OnlinehelpModule' );
            $userIdColumn = $module['userIdColumn'];
        }

protected/modules/onlinehelp/views/editor/_form.php
<div class="form">

<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
    'id'=>'online-help-form',
    'enableAjaxValidation'=>false,
    'type'=>'horizontal',
    'htmlOptions'=>array('class'=>'well'),
    'focus'=>array($model,$model->isNewRecord ? 'title' : 'content'),
)); ?>

    <p class="help-block"><?php echo sprintf(Chtml::encode(Yii::t('onlinehelp','Fields with %s are required.')),'<span class="required">*</span>'); ?></p>

    <?php echo $form->errorSummary($model); ?>

    <?php echo $form->textFieldRow($model,'title',array('class'=>'span5','maxlength'=>255, 'title'=>Yii::t('onlinehelp','Enter a title for this online help'))); ?>

    <?php echo $form->textFieldRow($model,'requestId',array('class'=>'span5','maxlength'=>255, 'title'=>Yii::t('onlinehelp','Enter a Yii request ID, e.g. post/admin here'))); ?>
    
    <?php echo $form->checkBoxRow($model,'isPageHelp', array('title'=>Yii::t('onlinehelp','Check if this help is for a page generally'))); ?>

    <?php echo $form->textFieldRow($model,'sequenceNbr',array('class'=>'span2', 'title'=>Yii::t('onlinehelp','This number is used to display consecutive help guiders in a defined sequence'))); ?>

    <?php echo $form->textFieldRow($model,'elementId',array('class'=>'span3', 'title'=>Yii::t('onlinehelp','If this is not a page help, enter a jQuery selector for the element the help guider shall be attached to.') )); ?>

    <?php echo $form->dropDownListRow($model,'guiderPosition', Onlinehelp::model()->guiderPositionOptions, array('class'=>'span3', 'empty'=>'(central)')); ?>

    <div class="control-group">
        <?php echo CHtml::activeLabelEx($model,'content',array('class'=>'control-label')); ?>
        <div class="controls">
            <?php $this->widget('application.extensions.diggindata.ddeditor.DDEditor',array(
                'model'=>$model,
                'attribute'=>'content',
                'previewRequest'=>'/onlinehelp/editor/preview',
                'htmlOptions'=>array('rows'=>7,'cssClass'=>'span6','style'=>'font-family:Courier', 'title'=>Yii::t('onlinehelp','Enter the help text (you may use Mardown syntax)') ),
                'additionalSnippets'=>array(
                    Yii::t('onlinehelp','Icons')=>array(
                        '<i class="icon-star"></i>' => Yii::t('onlinehelp','Create New Item'),
                        '<i class="icon-eye-open"></i>' => Yii::t('onlinehelp','View Item'),
                        '<i class="icon-pencil"></i>' => Yii::t('onlinehelp','Update Item'),
                        '<i class="icon-remove"></i>' => Yii::t('onlinehelp','Remove Item'),
                        '<i class="icon-th-list"></i>' => Yii::t('onlinehelp','Manage Items'),
                        '<i class="icon-th-large"></i>' => Yii::t('onlinehelp','List Items'),
                    ),
                    //Yii::t('onlinehelp','App. Pages') => $pages,
                ),
            )); ?>
            <?php echo CHtml::error($model,'content'); ?>    
        </div>
    </div>
    
    <?php if(!$model->isNewRecord) echo $form->checkBoxRow( $model, 'saveAsNew', array( 'title'=>Yii::t('onlinehelp','Save as a new item, keeping the original one')) ); ?>

    <div class="form-actions">
        <?php $this->widget('bootstrap.widgets.TbButton', array(
            'buttonType'=>'submit',
            'type'=>'primary',
            'label'=>$model->isNewRecord ? Yii::t('onlinehelp','Create') : Yii::t('onlinehelp','Save'),
            'icon'=>'ok white',
        )); ?>
        <?php $this->widget('bootstrap.widgets.TbButton', array(
            'buttonType'=>'reset', 
            'icon'=>'repeat', 
            'label'=>Yii::t('onlinehelp','Reset'))); ?>
    </div>

<?php $this->endWidget(); ?>


</div><!-- form -->

protected/modules/onlinehelp/views/editor/_search.php
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
    'action'=>Yii::app()->createUrl($this->route),
    'method'=>'get',
)); ?>

    <?php echo $form->textFieldRow($model,'id',array('class'=>'span5')); ?>

    <?php echo $form->textFieldRow($model,'title',array('class'=>'span5','maxlength'=>255)); ?>

    <?php echo $form->textAreaRow($model,'content',array('rows'=>6, 'cols'=>50, 'class'=>'span8')); ?>

    <?php echo $form->textFieldRow($model,'tsCreated',array('class'=>'span5')); ?>

    <?php echo $form->textFieldRow($model,'userIdCreated',array('class'=>'span5')); ?>

    <?php echo $form->textFieldRow($model,'tsUpdated',array('class'=>'span5')); ?>

    <?php echo $form->textFieldRow($model,'userIdUpdated',array('class'=>'span5')); ?>

    <div class="form-actions">
        <?php $this->widget('bootstrap.widgets.TbButton', array(
            'buttonType'=>'submit',
            'type'=>'primary',
            'label'=>Yii::t('onlinehelp','Search'),
        )); ?>
    </div>

<?php $this->endWidget(); ?>

protected/modules/onlinehelp/views/editor/_view.php
<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id),array('view','id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('title')); ?>:</b>
	<?php echo CHtml::encode($data->title); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('content')); ?>:</b>
	<?php echo CHtml::encode($data->content); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('tsCreated')); ?>:</b>
	<?php echo CHtml::encode($data->tsCreated); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('userIdCreated')); ?>:</b>
	<?php echo CHtml::encode($data->userIdCreated); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('tsUpdated')); ?>:</b>
	<?php echo CHtml::encode($data->tsUpdated); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('userIdUpdated')); ?>:</b>
	<?php echo CHtml::encode($data->userIdUpdated); ?>
	<br />


</div>

protected/modules/onlinehelp/views/editor/admin.php
<?php
$this->breadcrumbs=array(
    // Module Yii::t('onlinehelp','MODULE_NAME')=>array('/MODULE_ID'),
    Yii::t('onlinehelp','Online Help Pages')=>array('index'),
    Yii::t('onlinehelp','Manage'),
);

$this->menu=array(
    array('label'=>Yii::t('onlinehelp','Create New Online Help Page'),'url'=>array('create'), 'icon'=>'star'),
    array('label'=>Yii::t('onlinehelp','List Online Help Pages'),'url'=>array('index'), 'icon'=>'th-large'),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
    $('.search-form').toggle();
    return false;
});
$('.search-form form').submit(function(){
    $.fn.yiiGridView.update('online-help-grid', {
        data: $(this).serialize()
    });
    return false;
});
");
?>

<h1><?php echo CHtml::encode(Yii::t('onlinehelp','Manage Online Help Pages')); ?></h1>

<p>
You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<?php echo CHtml::link(Yii::t('onlinehelp','Advanced Search'),'#',array('class'=>'search-button btn')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
    'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('bootstrap.widgets.TbGridView',array(
    'id'=>'online-help-grid',
    'dataProvider'=>$model->search(),
    'filter'=>$model,
    'columns'=>array(
        array(
            'class'=>'bootstrap.widgets.TbButtonColumn',
            'template'=>'{view}&nbsp;&nbsp;{update}',
        ),
        // 'id',
        'requestId',
        'title',
        array(
            'name'=>'isPageHelp',
            'type'=>'boolean',
            'htmlOptions'=>array('style'=>'text-align:center'),
        ),
        array(
            'name'=>'sequenceNbr',
            'htmlOptions'=>array('style'=>'text-align:center'),
        ),
        array(
            'name'=>'elementId',
            'value'=>'$data->elementId!=="" ? $data->elementId : "(n.a.)"',
        ),
        /*
        array(
            'name'=>'tsCreated',
            'type'=>'raw',
            'value'=>'Chtml::encode(Yii::app()->dateFormatter->formatDateTime($data->tsCreated,"medium","short"))',
        ),
        array(
            'name'=>'userIdCreated',
            'value'=>'$data->userCreated->recordName',
        ),
        array(
            'name'=>'tsUpdated',
            'type'=>'raw',
            'value'=>'$data->tsUpdated==0 ? "-" : Chtml::encode(Yii::app()->dateFormatter->formatDateTime($data->tsUpdated,"medium","short"))',
        ),
        array(
            'name'=>'userIdUpdated',
            'value'=>'$data->userIdUpdated==0 ? "-" : $data->userUpdated->recordName',
        ),
         */
        array(
            'class'=>'bootstrap.widgets.TbButtonColumn',
            'template'=>'{delete}',
        ),
    ),
)); ?>

protected/modules/onlinehelp/views/editor/create.php
<?php
$this->breadcrumbs=array(
    // Module Yii::t('onlinehelp','MODULE_NAME')=>array('/MODULE_ID'),
	Yii::t('onlinehelp','Online Help Pages')=>array('admin'),
	Yii::t('onlinehelp','Create'),
);

$this->menu=array(
    array('label'=>Yii::t('onlinehelp','List Online Help Pages'),'url'=>array('index'), 'icon'=>'th-large'),
	array('label'=>Yii::t('onlinehelp','Manage Online Help Pages'),'url'=>array('admin'), 'icon'=>'th-list'),
);
?>

<h1><?php echo CHtml::encode(Yii::t('onlinehelp','Create a New Online Help Page')); ?></h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/modules/onlinehelp/views/editor/index.php
<?php
$this->breadcrumbs=array(
    // Module Yii::t('onlinehelp','MODULE_NAME')=>array('/MODULE_ID'),
    Yii::t('onlinehelp','Online Help Pages'),
);

$this->menu=array(
    array('label'=>Yii::t('onlinehelp','Create New Online Help Page'),'url'=>array('create'), 'icon'=>'star'),
	array('label'=>Yii::t('onlinehelp','Manage Online Help Pages'),'url'=>array('admin'), 'icon'=>'th-list'),
);
?>

<h1><?php echo CHtml::encode(Yii::t('onlinehelp','Online Help Pages')); ?></h1>

<?php $this->widget('bootstrap.widgets.TbListView',array(
	'dataProvider'=>$dataProvider,
    'itemView'=>'_view',
    'template'=>'{sorter}{pager}{summary}{items}{sorter}{pager}',
    'sortableAttributes'=>array(
    'title',
    'content',
    'tsCreated',
    // TODO: Uncomment the following attributes to show them as sort links in list view
// 'userIdCreated',
    // 'tsUpdated',
    // 'userIdUpdated',
    ),
)); ?>

protected/modules/onlinehelp/views/editor/update.php
<?php
$this->breadcrumbs=array(
    // Module Yii::t('onlinehelp','MODULE_NAME')=>array('/MODULE_ID'),
	Yii::t('onlinehelp','Online Help Pages')=>array('admin'),
	$model->title=>array('view','id'=>$model->id),
	Yii::t('onlinehelp','Update'),
);

$this->menu=array(
    array('label'=>Yii::t('onlinehelp','Create New Online Help Page'),'url'=>array('create'), 'icon'=>'star'),
	array('label'=>Yii::t('onlinehelp','View Online Help Page'),'url'=>array('view','id'=>$model->id), 'icon'=>'eye-open'),
	array('label'=>Yii::t('onlinehelp','List Online Help Pages'),'url'=>array('index'), 'icon'=>'th-large'),
	array('label'=>Yii::t('onlinehelp','Manage Online Help Pages'),'url'=>array('admin'), 'icon'=>'th-list'),
);
?>

<h1><?php echo CHtml::encode(Yii::t('onlinehelp','Update Online Help Page {recordName}',array('{recordName}'=>$model->recordName))); ?></h1>

<?php echo $this->renderPartial('_form',array('model'=>$model)); ?>